### ISSUE TITLE
"supplied shell script" as mentioned in README does not exist

### ISSUE THREAD

**Issue by wentam** [performantp/x52MFD#1]
Line 20 in the README refers to a non-existent shell script. 

If the only thing the shell script does is pass arguments on to fgfs, I also suggest mentioning the specific arguments for those who use ~/.fgfsrc

**Comment by wentam** [comment]
For anyone wanting to use this right away, I've looked in the source and figured out the command line argument needed to run this:  --generic=socket,out,10,127.0.0.1,1234,udp,x52

**Comment by performantp** [comment]
totally my bad - forgot to upload
