### ISSUE TITLE
Suggestion: switch between comm/nav with the joystick's mode selector

### ISSUE THREAD

**Issue by wentam** [performantp/x52MFD#4]
The x52pro has 3 joystick "modes" that can be switched between with a cool selector on the top of the stick. The MFD doesn't have enough lines to display all of the frequencies, so why not use the mode selector to switch what's displayed?

**Comment by performantp** [comment]
This is just a really early version - so there are many improvements to make :)
I've had a similar idea: Use the roller knob to the right of the MFD to flip through Frequencies. As far as I know - this would require use of the joystick library (which I think supports those buttons)

**Comment by wentam** [comment]
In case I ever feel like taking a shot at this: do you have a preference on what joystick library gets used?

**Comment by performantp** [comment]
Feel free :)
No not really, would be nice if it were in the debian/ubuntu repos - but use what you think is best.
I did some tests with the code from this guy: 
http://scaryreasoner.wordpress.com/2008/02/22/programming-joysticks-with-linux/
There may be better solutions though.
