### ISSUE TITLE
How are the frequencies to be incremented

### ISSUE THREAD

**Issue by performantp** [performantp/x52MFD#8]
I hear there are different amounts by which the various frequencies should be incremented/decremented?

What are they?

**Comment by wentam** [comment]
found a couple:
COM: steps of 25kHz
NAV: "navigation receiver uses a 50kHz raster" (don't know what it means)

**Comment by performantp** [comment]
I found out, raster basically means the same as step - it's the amount the frequencies should be in/decremented in each step.
